repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=88]
        language_version: python3.8
  - repo: https://github.com/PyCQA/pylint
    rev: v3.2.7
    hooks:
      - id: pylint
        language_version: python3
        args:
          - --disable=invalid-name,missing-module-docstring,import-error,missing-function-docstring,missing-class-docstring,too-few-public-methods,line-too-long,too-many-arguments,unused-argument,undefined-variable,fixme,useless-parent-delegation
