#:kivy 2.1.0     

<AddSnackScreenContent>:
    rows: 1
    padding: 30
    spacing: 30
    GridLayout:
        size_hint: (0.5, 1)
        cols:1
        GridLayout:
            cols: 1
            Label:
                text_size: self.size
                size_hint_y: None
                height: 30
                text: "Snack name"
                bold: True
            TextInput:
                id: snackNameTextInput
                write_tab: False
                hint_text: "Enter snack name"
                size_hint_y: None
                height: 40
                padding: [10, 10]
            Label:
                text_size: self.size
                size_hint_y: None
                height: 30
                text: "Quantity"
                bold: True
            TextInput:
                id: snackQuantityTextInput
                write_tab: False
                hint_text: "Enter number of snacks"
                size_hint_y: None
                height: 40
                padding: [10, 10]
            Label:
                text_size: self.size
                size_hint_y: None
                height: 30
                text: "Purchase price"
                bold: True
            TextInput:
                id: snackTotalPriceTextInput
                write_tab: False
                hint_text: "Enter total purchase price of snack"
                size_hint_y: None
                height: 40
                padding: [10, 10]
        GridLayout:
            rows: 1
            size_hint: (1, None)
            height: self.minimum_height
            SmallConfirmButton:
                on_press: root.onConfirm()
            Widget: # Horizontal Spacer
                size_hint: (1, None)
                height: 50
            SmallCancelButton:
                on_press: root.onCancel()

    GridLayout:
        cols: 1
        size_hint: (0.5, 1)
        padding: [5, 60, 5, 0]
        spacing: 10
        Label:
            font_size: "30sp"
            size_hint_y: None
            height: 30
            text: "This change will add"
            bold: True
        Label:
            id: numberOfItemsLabel
            font_size: "30sp"
            size_hint_y: None
            height: 30
            text: "? of ?"
        Label:
            font_size: "30sp"
            size_hint_y: None
            height: 30
            text: "which will cost users"
            bold: True
        Label:
            id: pricePerItemLabel
            font_size: "30sp"
            size_hint_y: None
            height: 30
            text: "0.00 credits per item"
