<BaseDeviceInfoLableWidget>:
    Label:
        id: deviceName
        text: 'deviceName' 

<BaseDeviceConnectionIndicatorWidget>:
    Image:
        id: deviceConnectionIndicator
        source: 'Images/ghost_red.png'
        size_hint: (1, 1)
        allow_stretch: False
        keep_ratio: True

<BaseDeviceInfoWidget>:
    id: info_box
    orientation: 'vertical'
    size_hint: (None, 1)
    width: '96dp'
    padding: 10