#:kivy 2.1.0


<BuyScreenContent>:
    cols: 1
    size_hint: (1, 1)
    padding: ['20dp', '5dp']
    GridLayout:
        rows: 1
        spacing: 30
        GridLayout:
            id: inventoryItemSelection
            cols: 1
            spacing: 5
            Label:
                text_size: self.size
                size_hint_y: None
                height: 24
                font_size: '22dp'
                text: "Inventory"
                bold: True
            ClickableTable:
                id: inventoryTable
                headerHeight: self.width / (15 / 2)
                entryHeight: self.width / (15 / 2)
                columns: ["Snack name", "Quantity", "Price"]
                columnExamples: ["Long snack", "30", "15.00"]
                onEntryPressed: root.itemClickedInInventory
        GridLayout:
            id: shoppingCartItemSelection
            cols: 1
            spacing: 5
            Label:
                text_size: self.size
                size_hint_y: None
                height: 24
                font_size: '22dp'
                text: "Shopping cart"
                bold: True
            ClickableTable:
                id: shoppingCartTable
                headerHeight: self.width / (15 / 2)
                entryHeight: self.width / (15 / 2)
                columns: ["Snack name", "Quantity", "Price"]
                columnExamples: ["Long snack", "30", "15.00"]
                onEntryPressed: root.itemClickedInShoppingCart
    GridLayout:
        rows: 1
        size_hint: (0.5, None)
        height: self.minimum_height
        spacing: 30
        padding: [0, 10]
        GridLayout:
            rows: 1
            size_hint_x: 0.5
            height: 50
            Label:
                text: 'Total price: 0.00 credits'
                id: totalPriceLabel
                size_hint: (1, None)
                height: 50
                font_size: 24
                text_size: self.size
                halign: 'left'
                valign: 'middle'
                bold: True
        GridLayout:
            rows: 1
            size_hint: (0.5, None)
            height: self.minimum_height
            SmallGreenButton:
                text: "Buy"
                on_press: root.onBuy()
            Widget: # Horizontal Spacer
                size_hint: (1, None)
                height: 50
            SmallOrangeButton:
                text: "Cancel"
                on_press: root.onCancel()
                

