#:kivy 2.1.0

<ClickableTableColumnLabel>:
    text: 'COLUMN NAME'
    bold: True
    font_size: self.height / 2

<ClickableTableEntry>:
    rows: 1
    size_hint_y: None
    on_press: root.onPress()
    markup: True
    canvas:
        Color:
            rgba: app.colors["secondary_background"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [(2, 2),(2, 2),(2, 2),(2, 2)]
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.10
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: 10, -10
            blur_radius: 15
            spread_radius: -5, -5
            border_radius: 2, 2, 2, 2


<ClickableTable>:
    rows: 1
    spacing: 30
    headerHeight: 50
    entryHeight: 50
    RoundedTwoColorGridLayout:
        cols: 1
        GridLayout:
            rows: 1
            size_hint: 1, None
            padding: [15, 5]
            height: root.headerHeight
            id: tableHeader
            canvas.after:
                Color:
                    rgba: (1, 1, 1, 1)
                SmoothLine:
                    width: 2.5
                    points: (self.x + 2.5, self.y + 2.5, self.x + self.width - 2.5, self.y + 2.5)
        GridLayout:
            rows: 1
            padding: [15, 5]
            RecycleView:
                id: rw
                viewclass: 'ClickableTableEntry'
                RecycleBoxLayout:
                    spacing: 10
                    default_size: None, root.entryHeight
                    default_size_hint: 1, None
                    size_hint_y: None
                    height: self.minimum_height
                    orientation: 'vertical'
