#:kivy 2.1.0

<ClickableTableColumnLabel>:
    size_hint_y: None
    text: 'COLUMN NAME'
    bold: True
    height: '40dp'
    font_size: '22dp'

<ClickableTableColumnEntryLabel>:
    rows: 1
    id: entry
    StencilView:
        Label:
            id: entryLabel
            text: 'ENTRY NAME'
            size_hint_x: None
            size_hint_y: None
            height: '50dp'
            width: entry.width
            pos: entry.pos
            markup: True
            font_size: '22dp'
            bold: True
            halign: "left"
            valign: 'middle'

<ClickableTableEntry>:
    rows: 1
    size_hint_y: None
    height: '50dp'
    on_press: root.onPress()
    markup: True
    padding: [10, 0]
    canvas:
        Color:
            rgba: app.colors["secondary_background"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [(2, 2),(2, 2),(2, 2),(2, 2)]
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.10
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: 10, -10
            blur_radius: 15
            spread_radius: -5, -5
            border_radius: 2, 2, 2, 2


<ClickableTable>:
    rows: 1
    spacing: 30
    RoundedTwoColorGridLayout:
        cols: 1
        padding: [0, 10]
        GridLayout:
            rows: 1
            size_hint: 1, None
            padding: ["10dp", 0, "10dp", "20dp"]
            height: '50dp'
            id: tableHeader
            canvas.after:
                Color:
                    rgba: (1, 1, 1, 1)
                SmoothLine:
                    width: 2.5
                    points: (self.x + 2.5, self.y + 2.5, self.x + self.width - 2.5, self.y + 2.5)
        RecycleView:
            id: rw
            viewclass: 'ClickableTableEntry'
            RecycleBoxLayout:
                spacing: 10
                padding: 10
                default_size: None, dp(50)
                default_size_hint: 1, None
                size_hint_y: None
                height: self.minimum_height
                orientation: 'vertical'
