#:kivy 2.1.0

<CreateUserScreen>:
    GridLayout:
        canvas:
            Color:
                rgba: app.colors["background"]
            Rectangle:
                pos: self.pos
                size: self.size
        cols: 1
        Widget: # Vertical Spacer
            size_hint_y: 0.1
        Label:
            text: "Create New User"
            bold: True
            halign: 'center'
            valign: 'middle'
            font_size: min(self.height/1.3, self.width/15)
            text_size: self.size
            size_hint_y: 0.2
            color: 'black'
        Widget: # Vertical Spacer
            size_hint_y: 0.1
        GridLayout:
            rows: 1
            size_hint_y: None
            height: self.minimum_height
            Widget: # Horizontal Spacer
                size_hint_x: 0.1
            RoundedTwoColorGridLayout:
                cols: 1
                spacing: self.width / 50
                padding: [20, 20]
                size_hint_y: None
                height: self.minimum_height
                TextInputWithHeader:
                    id: firstNameInput
                    size_factor: self.parent.width / 25
                    header_text: "First name"
                    hint_text: "Enter first name"
                TextInputWithHeader:
                    id: lastNameInput
                    size_factor: self.parent.width / 25
                    header_text: "Last name"
                    hint_text: "Enter last name"
                TextInputWithHeader:
                    id: cardIdInput
                    size_factor: self.parent.width / 25
                    header_text: "Login card"
                    hint_text: "Tap card to register (optional)"
                    disable_input: True
            Widget: # Horizontal Spacer
                size_hint_x: 0.1
        Widget: # Vertical Spacer
            size_hint_y: 0.1
        GridLayout:
            rows: 1
            size_hint_y: None
            height: self.minimum_height
            Widget: # Horizontal Spacer
                size_hint: (1, None)
                height: 100
            OrangeButton:
                text: "Cancel"
                width: self.parent.width / 3
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.cancel()
            Widget: # Horizontal Spacer
                size_hint: (1, None)
                height: 100
            GreenButton:
                text: "Register"
                width: self.parent.width / 3
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.registerUser()
            Widget: # Horizontal Spacer
                size_hint: (1, None)
                height: 100
        Widget: # Vertical Spacer
            size_hint_y: 0.1
