#:kivy 2.1.0     

<CreateUserOrLinkCardPopup>:
    id: errorMessagePopup
    size_hint: (0.9, 0.9)
    RoundedTwoColorGridLayout:
        cols: 1
        padding: 20
        spacing: 20
        Label:
            size_hint_y: None
            height: 56
            font_size: 48
            text_size: self.size
            halign: 'center'
            valign: 'middle'
            bold: True            
            text: 'Greetings, who are you?'
        GridLayout:
            rows: 1
            GridLayout:
                cols: 1
                padding: [0, 10]
                Label:
                    size_hint_y: None
                    height: 24
                    font_size: 22
                    text_size: self.size
                    halign: 'center'
                    valign: 'middle'
                    bold: True            
                    text: 'Create a new user?'
                Label:
                    font_size: 22
                    text_size: self.size
                    halign: 'center'
                    valign: 'middle'
                    bold: True            
                    text: 'You can create a new user that has this card linked to it.'
                GridLayout:
                    rows: 1
                    size_hint_y: None
                    height: 50
                    Widget: # Horizontal Spacer
                        size_hint: (1, None)
                        height: 50
                    SmallGreenButton:
                        text: "Create user"
                        on_press: root.createUserPressed()
                    Widget: # Horizontal Spacer
                        size_hint: (1, None)
                        height: 50
            GridLayout:
                size_hint: (None, 1)
                width: 30
                cols: 1
                canvas.after:
                    Color:
                        rgba: (1, 1, 1, 1)
                    SmoothLine:
                        width: 2.5
                        points: (self.x + (self.width/2), self.top, self.x + (self.width/2), self.y)
            GridLayout:
                cols: 1
                padding: [0, 10, 0, 0]
                Label:
                    size_hint_y: None
                    height: 24
                    font_size: 22
                    text_size: self.size
                    halign: 'center'
                    valign: 'middle'
                    bold: True            
                    text: 'Link card to existing user?'
                Label:
                    font_size: 22
                    text_size: self.size
                    multi_line: True
                    halign: 'center'
                    valign: 'middle'
                    bold: True            
                    text: 'You can link this card to an existing user or update an existing user\'s card.'
                GridLayout:
                    rows: 1
                    size_hint_y: None
                    height: 50
                    Widget: # Horizontal Spacer
                        size_hint: (1, None)
                        height: 50
                    SmallGreenButton:
                        text: "Link card"
                        on_press: root.linkCardPressed()
                    Widget: # Horizontal Spacer
                        size_hint: (1, None)
                        height: 50
        GridLayout:
            rows: 1
            size_hint_y: None
            height: 50
            Widget: # Horizontal Spacer
                size_hint: (1, None)
                height: 50
            SmallOrangeButton:
                text: "Close"
                on_press: root.dismiss()
            Widget: # Horizontal Spacer
                size_hint: (1, None)
                height: 50