#:kivy 2.1.0     

<CreditsAnimationPopup>:
    size_hint: (0.8, 0.5)
    auto_dismiss: True
    RoundedTwoColorGridLayout:
        center_x: True
        cols: 1
        size_hint: (1, 1)
        BoxLayout:
            orientation: "vertical"
            size_hint: (1, .9)
            Label:
                id: titleLabel
                text_size: self.size
                padding: 10
                halign: 'center'
                valign: 'middle'
                font_size: 42
                bold: True
                text: 'TITLE'
                
            Label:
                id: creditsLabel
                text_size: self.size
                padding: 10
                halign: 'center'
                valign: 'middle'
                font_size: 32
                bold: True
                text: 'Your credits: ??'