#:kivy 2.1.0

<EditUserScreenContent>:
    cols: 1
    padding: 20
    spacing: 60
    GridLayout:
        cols: 1
        size_hint_y: None
        height: self.minimum_height
        padding: [150, 0]
        spacing: 10
        TextInputWithHeader:
            id: firstNameInput
            header_text: "First name"
            hint_text: "Enter first name"
        TextInputWithHeader:
            id: lastNameInput
            header_text: "Last name"
            hint_text: "Enter last name"
        TextInputWithHeader:
            id: creditsInput
            header_text: "Credits"
            hint_text: "Enter credits"
            input_filter: "float"
        TextInputWithHeader:
            id: cardIdInput
            header_text: "Login card"
            hint_text: "Blipp card to register (optional)"
            disable_input: True
    GridLayout:
        rows: 1
        size_hint: (1, None)
        height: self.minimum_height
        padding: [20, 0]
        MediumConfirmButton:
            on_press: root.onConfirm()
        Widget: # Horizontal Spacer
            size_hint: (1, None)
            height: 75
        MediumCancelButton:
            on_press: root.onCancel()
        Widget: # Horizontal Spacer
            size_hint: (1, None)
            height: 75
        MediumRemoveButton:
            on_press: root.onRemove()


<RemoveUserConfirmationPopup>:
    title: "Remove user"
    size_hint: (None,None)
    size: (700,400)
    GridLayout:
        cols: 1
        padding: 30
        spacing: 30
        Label:
            id: areYouSureLabel
            text_size: self.size
            font_size: 32
            halign: 'center'
            valign: 'top'
            text: "Are you sure you want to \nremove FIRSTNAME?"
            bold: True
        GridLayout:
            rows: 1
            size_hint: (1, None)
            height: self.minimum_height
            padding: [60, 0]
            MediumCancelButton:
                on_press: root.onCancel()
            Widget: # Horizontal Spacer
                size_hint: (1, None)
                height: 75
            MediumRemoveButton:
                on_press: root.onRemove()
            
            
