#:kivy 2.1.0     

<EditSummaryHeading@Label>:
    font_size: 18
    text_size: self.size
    size_hint_y: None
    height: 20
    halign: 'left'
    valign: 'middle'
    bold: True

<EditSummaryData@Label>:
    font_size: 16
    text_size: self.size
    size_hint_y: None
    height: 20
    halign: 'left'
    valign: 'middle'

<EditSummaryPopup>:
    size_hint: (0.4, 0.65)
    auto_dismiss: True
    GridLayout:
        canvas:
            Color:
                rgba: app.colors["secondary_background"]
            SmoothRoundedRectangle:
                pos: self.pos
                size: self.size
        cols: 1
        padding: '10dp'
        spacing: '10dp'
        GridLayout:
            cols: 1
            padding: [5, 0, 5, 0]
            spacing: 10
            GridLayout:
                cols: 1
                spacing: 5
                EditSummaryHeading:
                    text: 'Edit date:'
                EditSummaryData:
                    text: 'DATA NOT SET'
                    id: editDateLabel
            GridLayout:
                cols: 1
                spacing: 5
                EditSummaryHeading:
                    text: 'Credits before edit:'
                EditSummaryData:
                    text: 'DATA NOT SET'
                    id: creditsBeforeEditLabel
            GridLayout:
                cols: 1
                spacing: 5
                EditSummaryHeading:
                    text: 'Credits after edit:'
                EditSummaryData:
                    text: 'DATA NOT SET'
                    id: creditsAfterEditLabel
        GridLayout:
            rows: 1
            size_hint: (1, None)
            height: self.minimum_height
            orientation: 'rl-tb'
            SmallOrangeButton:
                text: "Close"
                on_press: root.dismiss()