#:kivy 2.1.0


<EditUsersScreenContent>:
    rows: 1
    size_hint: (1, 1)
    padding: '20dp'
    canvas:
        Color:
            rgba: 0.3, 0.3, 0.3, 1
        Rectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        cols: 1
        size_hint: 1, 1
        canvas.after:
            Color:
                rgba: .5, .5, .5, 1
            Line:
                width: 2
                rectangle: self.x, self.y, self.width, self.height
        GridLayout:
            rows: 1
            size_hint: 1, None
            height: '50dp'
            canvas.after:
                Color:
                    rgba: .5, .5, .5, 1
                Line:
                    width: 2
                    rectangle: self.x, self.y, self.width, self.height
            Label:
                size_hint: 1, None
                text: 'First Name'
                bold: True
                height: '50dp'
            Label:
                size_hint: 1, None
                text: 'Last Name'
                bold: True
                height: '50dp'
            Label:
                size_hint: 1, None
                text: 'ID'
                bold: True
                height: '50dp'
            Label:
                size_hint: 1, None
                text: 'Total Credits'
                bold: True
                height: '50dp'
        ScrollView:
            do_scroll_x: False
            GridLayout:
                id: editUsersScrollViewLayout
                cols: 1
                padding: "10dp"
                spacing: 10
                size_hint_y: None
                height: self.minimum_height

<UserEntry>:
    rows: 1
    size_hint_y: None
    height: '50dp'
    on_press: root.onPress()
    canvas.after:
        Color:
            rgba: .5, .5, .5, 1
        Line:
            width: 2
            rectangle: self.x, self.y, self.width, self.height
    Label:
        id: userFirstNameLabel
        text: 'First Name'
        size_hint: 1, None
        height: '50dp'
    Label:
        id: userLastNameLabel
        text: 'Last Name'
        size_hint: 1, None
        height: '50dp'
    Label:
        id: userIdLabel
        text: 'ID'
        size_hint: 1, None
        height: '50dp'
    Label:
        id: userTotalCreditsLabel
        text: 'Total Credits'
        size_hint: 1, None
        height: '50dp'
