#:kivy 2.1.0     

<EditSummaryHeading@Label>:
    font_size: self.width / 20
    text_size: self.size
    size_hint_y: None
    height: self.width / 18
    halign: 'left'
    valign: 'middle'
    bold: True

<EditSummaryData@Label>:
    font_size: self.width / 22
    text_size: self.size
    size_hint_y: None
    height: self.width / 20
    halign: 'left'
    valign: 'middle'

<EditSummaryPopup>:
    size_hint: (0.5, None)
    auto_dismiss: True
    GridLayout:
        cols: 1
        id: editSummaryPopupContent
        size_hint_y: None
        height: self.minimum_height
        padding: 10
        spacing: 10
        canvas:
            Color:
                rgba: app.colors["secondary_background"]
            SmoothRoundedRectangle:
                pos: self.pos
                size: self.size
        GridLayout:
            cols: 1
            size_hint_y: None
            height: self.minimum_height
            spacing: 10
            GridLayout:
                cols: 1
                spacing: 5
                size_hint_y: None
                height: self.minimum_height
                EditSummaryHeading:
                    text: 'Edit date:'
                EditSummaryData:
                    text: 'DATA NOT SET'
                    id: editDateLabel
            GridLayout:
                cols: 1
                spacing: 5
                size_hint_y: None
                height: self.minimum_height
                EditSummaryHeading:
                    text: 'Credits before edit:'
                EditSummaryData:
                    text: 'DATA NOT SET'
                    id: creditsBeforeEditLabel
            GridLayout:
                cols: 1
                spacing: 5
                size_hint_y: None
                height: self.minimum_height
                EditSummaryHeading:
                    text: 'Credits after edit:'
                EditSummaryData:
                    text: 'DATA NOT SET'
                    id: creditsAfterEditLabel
        GridLayout:
            rows: 1
            size_hint: (1, None)
            height: self.minimum_height
            orientation: 'rl-tb'
            OrangeButton:
                text: "Close"
                width: self.parent.width / 2.5
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.dismiss()