#:kivy 2.1.0     



<BoolSettingRow>:
    rows: 1
    size_hint: (1, None)
    height: self.width / 12
    padding: [20, 5]
    canvas:
        Color:
            rgba: app.colors["secondary_background"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [(2, 2),(2, 2),(2, 2),(2, 2)]
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.10
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: 10, -10
            blur_radius: 15
            spread_radius: -5, -5
            border_radius: 2, 2, 2, 2
    Label:
        id: settingName
        text: "Settings item"
        text_size: self.size
        halign: 'left'
        valign: 'middle'
        bold: True
        font_size: self.height / 2
    GridLayout:
        rows: 1
        size_hint_x: None
        width: self.parent.height * 4
        Widget: # Horizontal Spacer
        BoxLayoutButton:
            on_press: root.onSettingChanged()
            size_hint: (None, None)
            height: self.parent.height
            width: self.height
            Image:
                id: toggleButtonImage
                source: 'Images/toggle-on.png'
        Widget: # Horizontal Spacer

<PaymentMethodOption>:
    background_normal: ''
    background_down: ''
    background_color: 1, 1, 1, 1
    color: 0, 0, 0, 1
    font_size: self.height / 1.5
    size_hint_y: None
    height: 40
    canvas.after:
        Color:
            rgba: 0, 0, 0, 1
        Line:
            rounded_rectangle: (self.x, self.y, self.width, self.height, 2, 2, 2, 2)


<EnumSettingRow>:
    rows: 1
    size_hint: (1, None)
    height: self.width / 12
    padding: [20, 5]
    canvas:
        Color:
            rgba: app.colors["secondary_background"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [(2, 2),(2, 2),(2, 2),(2, 2)]
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.10
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: 10, -10
            blur_radius: 15
            spread_radius: -5, -5
            border_radius: 2, 2, 2, 2
    Label:
        id: settingName
        text: "Settings item"
        text_size: self.size
        halign: 'left'
        valign: 'middle'
        bold: True
        font_size: self.height / 2
    BoxLayout:
        size_hint_x: None
        width: self.parent.height * 4
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            SmoothRoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [(2, 2), (2, 2), (2, 2), (2, 2)]
        canvas.after:
            Color:
                rgba: 0, 0, 0, 1
            Line:
                rounded_rectangle: (self.x, self.y, self.width, self.height, 2, 2, 2, 2)
        Spinner:
            option_cls: "PaymentMethodOption"
            id: spinner
            font_size: self.height / 1.5
            color: 0, 0, 0, 1
            background_normal: ''
            background_down: ''
            background_color: 1, 1, 1, 1
            size_hint: 1, 1

<StatusSettingRow>:
    rows: 1
    size_hint: (1, None)
    height: self.width / 12
    padding: [20, 5]
    canvas:
        Color:
            rgba: app.colors["secondary_background"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [(2, 2),(2, 2),(2, 2),(2, 2)]
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.10
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: 10, -10
            blur_radius: 15
            spread_radius: -5, -5
            border_radius: 2, 2, 2, 2
    Label:
        id: settingName
        text: "Status"
        text_size: self.size
        halign: 'left'
        valign: 'middle'
        bold: True
        font_size: self.height / 2
    Label:
        id: statusLabel
        text: "Checking..."
        text_size: self.size
        halign: 'center'
        valign: 'middle'
        font_size: self.height / 2
        size_hint_x: None
        width: self.parent.height * 4

<ButtonOptionRow>:
    rows: 1
    size_hint: (1, None)
    height: self.width / 12
    padding: [20, 5]
    canvas:
        Color:
            rgba: app.colors["secondary_background"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [(2, 2),(2, 2),(2, 2),(2, 2)]
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.10
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: 10, -10
            blur_radius: 15
            spread_radius: -5, -5
            border_radius: 2, 2, 2, 2
    Label:
        id: optionName
        text: "Option item"
        text_size: self.size
        halign: 'left'
        valign: 'middle'
        bold: True
        font_size: self.height / 2
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'
        size_hint_x: None
        width: self.parent.height * 4
        RedButton:
            id: button
            text: "Remove"
            width: self.parent.width / 2
            height: self.width / 3
            text_size: self.height / 2
            on_release: root.on_release()

<FloatSettingRow>:
    rows: 1
    size_hint: (1, None)
    height: self.width / 12
    padding: [20, 5]
    canvas:
        Color:
            rgba: app.colors["secondary_background"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [(2, 2),(2, 2),(2, 2),(2, 2)]
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.10
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: 10, -10
            blur_radius: 15
            spread_radius: -5, -5
            border_radius: 2, 2, 2, 2
    Label:
        id: settingName
        text: "Settings item"
        text_size: self.size
        halign: 'left'
        valign: 'middle'
        bold: True
        font_size: self.height / 2
    TextInput:
        id: textInput
        write_tab: False
        multiline: False
        font_size: self.height / 1.5
        halign: "center"
        valign: "middle"
        hint_text: "Enter amount"
        input_filter: "float"
        size_hint_x: None
        width: self.parent.height * 4

<StringSettingRow>:
    rows: 1
    size_hint: (1, None)
    height: self.width / 12
    padding: [20, 5]
    canvas:
        Color:
            rgba: app.colors["secondary_background"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [(2, 2),(2, 2),(2, 2),(2, 2)]
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.10
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: 10, -10
            blur_radius: 15
            spread_radius: -5, -5
            border_radius: 2, 2, 2, 2
    Label:
        id: settingName
        text: "Settings item"
        text_size: self.size
        halign: 'left'
        valign: 'middle'
        bold: True
        font_size: self.height / 2
    TextInput:
        id: textInput
        write_tab: False
        multiline: False
        font_size: self.height / 1.5
        halign: "center"
        valign: "middle"
        hint_text: "Enter amount"
        input_filter: "float"
        size_hint_x: None
        width: self.parent.height * 4

<SettingsSection>:
    cols: 1
    size_hint: 1, None
    height: self.minimum_height

    Label:
        id: sectionNameLabel
        text_size: self.size
        size_hint_y: None
        height: self.parent.width / 24
        font_size: self.parent.width / 26
        text: "SECTION NAME"
        bold: True
        
    GridLayout:
        id: sectionContent
        cols: 1
        padding: 10
        spacing: self.parent.width / 80
        size_hint_y: None
        height: self.minimum_height


<EditSystemSettingsScreen>:
    rows: 2
    cols: 1
    NavigationHeader:
        id: header
        use_back_button: True
        page_name: "System Settings"
    GridLayout:
        cols: 1
        padding: 20
        canvas:
            Color:
                rgba: app.colors["background"]
            Rectangle:
                pos: self.pos
                size: self.size
        RoundedTwoColorGridLayout:
            rows: 1
            padding: 10
            ScrollView:
                id: settingsScrollView
                do_scroll_x: False
                GridLayout:
                    id: settingsLayout
                    cols: 1
                    padding: 10
                    spacing: 10
                    size_hint_y: None
                    height: self.minimum_height
                    