#:kivy 2.1.0     

<EditSummaryHeading@Label>:
    font_size: 18
    text_size: self.size
    size_hint_y: None
    height: 20
    halign: 'left'
    valign: 'middle'
    bold: True

<EditSummaryData@Label>:
    font_size: 16
    text_size: self.size
    size_hint_y: None
    height: 20
    halign: 'left'
    valign: 'middle'

<EditSummaryPopup>:
    size_hint: (0.4, 0.65)
    auto_dismiss: True
    title: "Edit summary"
    GridLayout:
        cols: 1
        size_hint: (1, 1)
        padding: '10dp'
        GridLayout:
            cols: 1
            size_hint: (1, 0.7)
            padding: [5, 0, 5, 0]
            spacing: 10
            GridLayout:
                cols: 1
                spacing: 5
                EditSummaryHeading:
                    text: 'Edit date:'
                EditSummaryData:
                    text: 'DATA NOT SET'
                    id: editDateLabel
            GridLayout:
                cols: 1
                spacing: 5
                EditSummaryHeading:
                    text: 'Credits before edit:'
                EditSummaryData:
                    text: 'DATA NOT SET'
                    id: creditsBeforeEditLabel
            GridLayout:
                cols: 1
                spacing: 5
                EditSummaryHeading:
                    text: 'Credits after edit:'
                EditSummaryData:
                    text: 'DATA NOT SET'
                    id: creditsAfterEditLabel
        GridLayout:
            rows: 1
            size_hint: (1, 0.3)
            padding: '10dp'
            orientation: 'rl-tb'
            BoxLayoutButton:
                on_press: root.dismiss()
                size_hint: (None, 1)
                width: '180dp'
                canvas:
                    Color:
                        rgba: 0.5, 0.0, 0.0, 1
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                
                Label:
                    bold: True
                    text: 'Close'
                    size_hint: (1, 1)