#:kivy 2.1.0


<EditUsersScreenContent>:
    rows: 1
    size_hint: (1, 1)
    padding: '20dp'
    ClickableTable:
        id: usersTable
        headerHeight: self.width / 15
        entryHeight: self.width / 15
        columns: ["First name", "Last name", "Login card", "Total credits"]
        columnExamples: ["LongName", "LongLastName", "1231231123", "100.00"]
        onEntryPressed: root.onUserEntryPressed

