#:kivy 2.1.0

<EditSnackScreen>:
    rows: 2
    cols: 1
    NavigationHeader:
        id: header
        use_settings_button: False
        page_name: "Edit Snack"
    GridLayout:
        cols: 1
        padding: 20
        canvas:
            Color:
                rgba: app.colors["background"]
            Rectangle:
                pos: self.pos
                size: self.size
        Widget: # Vertical Spacer
        GridLayout:
            rows: 1
            size_hint_y: None
            padding: [self.width / 8, 0]
            height: self.minimum_height
            RoundedTwoColorGridLayout:
                cols: 1
                padding: 20
                spacing: self.width / 50
                size_hint_y: None
                height: self.minimum_height
                TextInputWithHeader:
                    id: snackNameInput
                    size_factor: self.parent.width / 30
                    header_text: "Snack Name"
                    hint_text: "Enter snack name"
                TextInputWithHeader:
                    id: snackQuantityInput
                    size_factor: self.parent.width / 30
                    header_text: "Quantity"
                    hint_text: "Enter quantity"
                    input_filter: "int"
                TextInputWithHeader:
                    id: snackPriceInput
                    size_factor: self.parent.width / 30
                    header_text: "Price"
                    hint_text: "Enter price"
                    input_filter: "currency"
        Widget: # Vertical Spacer
        GridLayout:
            rows: 1
            size_hint: (1, None)
            height: self.minimum_height
            Widget: # Horizontal Spacer
            RedButton:
                id: removeButton
                text: "Remove"
                width: self.parent.width / 4
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.onRemove()
            Widget: # Horizontal Spacer
            OrangeButton:
                id: cancelButton
                text: "Cancel"
                width: self.parent.width / 4
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.onCancel()
            Widget: # Horizontal Spacer
            GreenButton:
                id: confirmButton
                text: "Confirm"
                width: self.parent.width / 4
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.onConfirm()
            Widget: # Horizontal Spacer
        Widget: # Vertical Spacer

