#:kivy 2.1.0

<EditSnackScreenContent>:
    cols: 1
    padding: 30
    spacing: 30
    GridLayout:
        cols: 1
        padding: [150, 0]
        spacing: 10
        LargeTextInputWithHeader:
            id: snackNameInput
            header_text: "Snack Name"
            hint_text: "Enter snack name"
        LargeTextInputWithHeader:
            id: snackQuantityInput
            header_text: "Quantity"
            hint_text: "Enter quantity"
            input_filter: "int"
        LargeTextInputWithHeader:
            id: snackPriceInput
            header_text: "Price"
            hint_text: "Enter price"
            input_filter: "float"

    GridLayout:
        rows: 1
        size_hint: (1, None)
        height: self.minimum_height
        padding: [20, 0]
        MediumConfirmButton:
            on_press: root.onConfirm()
        Widget: # Horizontal Spacer
            size_hint: (1, None)
            height: 75
        MediumCancelButton:
            on_press: root.onCancel()
        Widget: # Horizontal Spacer
            size_hint: (1, None)
            height: 75
        MediumRemoveButton:
            on_press: root.onRemove()


<RemoveSnackConfirmationPopup>:
    title: "Remove snack"
    size_hint: (None,None)
    size: (700,400)
    GridLayout:
        cols: 1
        padding: 30
        spacing: 30
        Label:
            id: areYouSureLabel
            text_size: self.size
            font_size: 32
            halign: 'center'
            valign: 'top'
            text: "Are you sure you want to \nremove SNACKNAME?"
            bold: True
        GridLayout:
            rows: 1
            size_hint: (1, None)
            height: self.minimum_height
            padding: [60, 0]
            MediumCancelButton:
                on_press: root.onCancel()
            Widget: # Horizontal Spacer
                size_hint: (1, None)
                height: 75
            MediumRemoveButton:
                on_press: root.onRemove()
            
