#:kivy 2.1.0     

<EditSnacksScreenHeader>:
    rows: 1
    size_hint: 1, 0.2
    canvas:
        Color:
            rgba: 0.8, 0.8, 0.8, 1
        Rectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        orientation: "lr-tb"
        rows: 1
        size_hint: 1, 1
        Label:
            id: welcomeTextLabel
            text: 'WelcomeText'
            halign: 'left'
            valign: 'middle'
            padding: ['20dp', 0, 0, 0]
            size_hint: (1, 1)
            text_size: self.size
            color: 'black'
            bold: True
    GridLayout:
        orientation: "rl-tb"
        rows: 1
        size_hint: 1, 1
        BoxLayoutButton:
            size_hint: None, 1
            width: '120dp'
            on_press: root.onLogoutButtonPressed()
            canvas:
                Color:
                    rgba: 0.7, 0.1, 0.1, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            
            Label:
                text: 'Log out'
                size_hint: (1, 1)

<EditSnacksScreenBody>:
    rows: 1
    size_hint: (1, 1)
    canvas:
        Color:
            rgba: 0.3, 0.3, 0.3, 1
        Rectangle:
            pos: self.pos
            size: self.size
    #padding: 30
    #spacing: 30
    ScrollView:
        pos_hint:{"center_x":0.5,"center_y":0.5}
        do_scroll_x: False
        id: editSnacksScrollView


<SnackEntry>:
    rows: 1
    Label:
        id: snackNameLabel
        text: 'Snack'
        size_hint: 1, None
        height: '10dp'


<EditSnacksScreen>:
    canvas:
        Color:
            rgba: .9, .9, .9, 1
        Rectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        id: editSnacksGridLayout
        cols: 1
