#:kivy 2.1.0     

<EditSnacksScreenContent>:
    rows: 1
    size_hint: (1, 1)
    padding: '20dp'
    canvas:
        Color:
            rgba: 0.3, 0.3, 0.3, 1
        Rectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        cols: 1
        size_hint: 1, 1
        canvas.after:
            Color:
                rgba: .5, .5, .5, 1
            Line:
                width: 2
                rectangle: self.x, self.y, self.width, self.height
        GridLayout:
            rows: 1
            size_hint: 1, None
            height: '50dp'
            canvas.after:
                Color:
                    rgba: .5, .5, .5, 1
                Line:
                    width: 2
                    rectangle: self.x, self.y, self.width, self.height
            Label:
                size_hint: 1, None
                text: 'Snack name'
                bold: True
                height: '50dp'
            Label:
                size_hint: 1, None
                text: 'Quantity'
                bold: True
                height: '50dp'
            Label:
                size_hint: 1, None
                text: 'Price'
                bold: True
                height: '50dp'
            Label:
                size_hint: 1, None
                text: 'Image ID'
                bold: True
                height: '50dp'
        ScrollView:
            do_scroll_x: False
            GridLayout:
                id: editSnacksScrollViewLayout
                cols: 1
                padding: "10dp"
                spacing: 10
                size_hint_y: None
                height: self.minimum_height

<SnackEntry>:
    rows: 1
    size_hint_y: None
    height: '50dp'
    on_press: root.onPress()
    canvas.after:
        Color:
            rgba: .5, .5, .5, 1
        Line:
            width: 2
            rectangle: self.x, self.y, self.width, self.height
    Label:
        id: snackNameLabel
        text: 'Snack'
        size_hint: 1, None
        height: '50dp'
    Label:
        id: snackQuantityLabel
        text: 'Snack'
        size_hint: 1, None
        height: '50dp'
    Label:
        id: snackPriceLabel
        text: 'Snack'
        size_hint: 1, None
        height: '50dp'
    Label:
        id: snackImageIdLabel
        text: 'Snack'
        size_hint: 1, None
        height: '50dp'

<AddSnackEntry>:
    rows: 1
    size_hint_y: None
    height: '50dp'
    on_press: root.onPress()
    canvas.after:
        Color:
            rgba: .5, .5, .5, 1
        Line:
            width: 2
            rectangle: self.x, self.y, self.width, self.height
    Label:
        text: 'Add a snack +'
        bold: True
        size_hint: 1, None
        height: '50dp'
