#:kivy 2.1.0     

<EMFReaderWidget>:
    size_hint: (1,1)
    canvasOpacity: 0.5
    canvas.after:
        Color:
            rgba: 0, 0, 0, self.canvasOpacity
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        id: ledbox
        orientation: 'vertical'
        size_hint: (.7, 1)
        padding: 10
        BoxLayout:
            id: ledIndicator
            orientation: 'horizontal'
            size_hint: (1, .5)
            canvas:
                Color:
                    rgba: 0, 0, 0, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            BoxLayout:
                size_hint: (.1, 1)        
            BoxLayout:
                id: led0
                size_hint: (.2, 1)
                canvas:
                    Color:
                        rgba: 0, 1, 0, 1
                    Ellipse:
                        pos: self.pos
                        size: self.size
            BoxLayout:
                size_hint: (.1, 1)         
            BoxLayout:
                id: led1
                size_hint: (.2, 1)
                canvas:
                    Color:
                        rgba: 0, 1, 0, 1
                    Ellipse:
                        pos: self.pos
                        size: self.size
            BoxLayout:
                size_hint: (.1, 1)            
            BoxLayout:
                id: led2
                size_hint: (.2, 1)
                canvas:
                    Color:
                        rgba: 1, 1, 0, 1
                    Ellipse:
                        pos: self.pos
                        size: self.size
            BoxLayout:
                size_hint: (.1, 1)            
            BoxLayout:
                id: led3
                size_hint: (.2, 1)
                canvas:
                    Color:
                        rgba: 1, 0, 0, 1
                    Ellipse:
                        pos: self.pos
                        size: self.size
            BoxLayout:
                size_hint: (.1, 1)            
            BoxLayout:
                id: led4
                size_hint: (.2, 1)
                canvas:
                    Color:
                        rgba: 1, 0, 0, 1
                    Ellipse:
                        pos: self.pos
                        size: self.size
            BoxLayout:
                size_hint: (.1, 1)            
        Slider:
            id: ledSlider
            size_hint: 1, .5
            padding: (self.width * .2) * 0.5 + 13
            max: 4
            value: 0
            step: 1
            on_value: root.OnLedNumChanged(self.value)
    BoxLayout:
        orientation: 'vertical'
        size_hint: (.3, 1)
        padding: 10
        spacing: 5
        BoxLayout:
            size_hint: (1,1)
            orientation: 'horizontal'
            valign: 'right'
            BoxLayout:
                size_hint: (.7, 1)
            Button:
                id: muteButton
                text: 'Unmute'
                on_press: root.OnMuteButtonChange()
                size_hint: (.3, 1)
        BoxLayout:
            size_hint: (1,1)
            orientation: 'horizontal'
            ToggleButton:
                id: fluctuationButton0
                text: '0'
                group: 'fluctuationMagnitudeButton'
                state: 'down'
                allow_no_selection: False
                on_press: root.OnFluctuationMagnitudeChanged(0)
            ToggleButton:
                id: fluctuationButton1
                text: '1'
                group: 'fluctuationMagnitudeButton'
                allow_no_selection: False
                on_press: root.OnFluctuationMagnitudeChanged(1)
            ToggleButton:
                id: fluctuationButton2
                text: '2'
                group: 'fluctuationMagnitudeButton'
                allow_no_selection: False
                on_press: root.OnFluctuationMagnitudeChanged(2)
        BoxLayout:
            size_hint: (1,1)
            orientation: 'horizontal'
            ToggleButton:
                id: fluctuationRateButton0
                text: 'L'
                group: 'fluctuationRateButton'
                state: 'down'
                allow_no_selection: False
                on_press: root.OnFluctuationRateChanged(0)
            ToggleButton:
                id: fluctuationRateButton1
                text: 'M'
                group: 'fluctuationRateButton'
                allow_no_selection: False
                on_press: root.OnFluctuationRateChanged(1)
            ToggleButton:
                id: fluctuationRateButton2
                text: 'H'
                group: 'fluctuationRateButton'
                allow_no_selection: False
                on_press: root.OnFluctuationRateChanged(2)
            
