#:kivy 2.1.0     

<ErrorMessagePopup>:
    id: errorMessagePopup
    size_hint: (0.5, 0.5)
    canvas:
        Color:
            rgba: app.colors["secondary_background"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        cols: 1
        padding: '10dp'
        spacing: '10dp'
        Label:
            id: errorMessagePopupLabel
            font_size: 18
            text_size: self.size
            halign: 'center'
            valign: 'middle'
            bold: True            
            text: 'UNDEFINED'
        GridLayout:
            rows: 1
            size_hint: (1, None)
            height: self.minimum_height
            orientation: 'rl-tb'
            SmallOrangeButton:
                text: "Close"
                on_press: root.dismiss()
