#:kivy 2.1.0     

<Header>:
    rows: 1
    size_hint: 1, 0.2
    canvas:
        Color:
            rgba: 0.392, 0.839, 0.859, 1
        Rectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        id: leftContent
        orientation: "lr-tb"
        rows: 1
        size_hint: 1, 1
        Label:
            id: welcomeTextLabel
            text: 'WelcomeText'
            halign: 'left'
            valign: 'middle'
            padding: ['20dp', 0, 0, 0]
            size_hint: (1, 1)
            text_size: self.size
            color: 'black'
            bold: True
    GridLayout:
        id: rightContent
        orientation: "rl-tb"
        rows: 1
        size_hint: 1, 1
        GridLayout:
            rows: 1
            size_hint: None, 1
            width: '130dp'
            padding: 10
            BoxLayoutButton:
                on_press: root.onLogoutButtonPressed()
                canvas:
                    Color:
                        rgba: app.colors["red_button"]
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                Label:
                    text: 'Log out'
                    font_size: "28sp"
                    bold: True
                    size_hint: (1, 1)

<Body>:
    rows: 1
    size_hint: (1, 1)
    canvas:
        Color:
            rgba: app.colors["background"]
        Rectangle:
            pos: self.pos
            size: self.size

<SettingsButton>:
    size_hint_x: None
    width: self.height
    on_press: root.onPressed()
    GridLayout:
        cols: 1
        padding: 10
        Image: 
            source: 'Images/wrench-alt.png'
            

<BackButton>:
    size_hint_x: None
    width: self.height
    on_press: root.onPressed()
    GridLayout:
        cols: 1
        padding: 10
        Image: 
            source: 'Images/leftArrow.png'

<HeaderBodyScreen>:
    canvas:
        Color:
            rgba: .9, .9, .9, 1
        Rectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        id: screenLayout
        cols: 1
