#:kivy 2.1.0


<HistoryScreenContent>:
    cols: 1
    size_hint: (1, 1)
    padding: '10dp'
    canvas:
        Color:
            rgba: 0.3, 0.3, 0.3, 1
        Rectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        cols: 1
        spacing: 5
        GridLayout:
            cols: 1
            size_hint: 1, 1
            canvas.after:
                Color:
                    rgba: .5, .5, .5, 1
                Line:
                    width: 2
                    rectangle: self.x, self.y, self.width, self.height
            GridLayout:
                rows: 1
                size_hint: 1, None
                height: '50dp'
                canvas.after:
                    Color:
                        rgba: .5, .5, .5, 1
                    Line:
                        width: 2
                        rectangle: self.x, self.y, self.width, self.height
                Label:
                    size_hint: 1, None
                    text: 'Date'
                    bold: True
                    height: '50dp'
                Label:
                    size_hint: 1, None
                    text: 'Credits before'
                    bold: True
                    height: '50dp'
                Label:
                    size_hint: 1, None
                    text: 'Credits after'
                    bold: True
                    height: '50dp'
                Label:
                    size_hint: 1, None
                    text: 'Type'
                    bold: True
                    height: '50dp'
            ScrollView:
                size_hint: 1, 1
                do_scroll_x: False
                GridLayout:
                    id: historyScrollViewLayout
                    cols: 1
                    padding: "10dp"
                    spacing: 10
                    size_hint_y: None
                    height: self.minimum_height
        
<HistoryEntry>:
    rows: 1
    size_hint_y: None
    height: '50dp'
    on_press: root.onPress()
    canvas.after:
        Color:
            rgba: .5, .5, .5, 1
        Line:
            width: 2
            rectangle: self.x, self.y, self.width, self.height
    Label:
        id: historyDateLabel
        text: 'TEMP'
        size_hint: 1, None
        height: '50dp'
    Label:
        id: historyCreditsBeforeLabel
        text: 'Snack'
        size_hint: 1, None
        height: '50dp'
    Label:
        id: historyCreditsAfterLabel
        text: 'Snack'
        size_hint: 1, None
        height: '50dp'
    Label:
        id: historyTypeLabel
        text: 'Snack'
        size_hint: 1, None
        height: '50dp'
