#:kivy 2.1.0     

<InsufficientFundsPopup>:
    id: errorMessagePopup
    size_hint: (0.5, 0.5)
    canvas:
        Color:
            rgba: app.colors["secondary_background"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        cols: 1
        padding: '20dp'
        Label:
            size_hint_y: None
            height: self.width / 8
            font_size: self.width / 10
            text_size: self.size
            halign: 'center'
            valign: 'middle'
            bold: True            
            text: 'Insufficient funds'
        Label:
            font_size: self.width / 16
            text_size: self.size
            halign: 'center'
            valign: 'middle'
            bold: True            
            text: 'Would you like to add funds now?'
        GridLayout:
            rows: 1
            size_hint: (1, None)
            height: self.minimum_height
            orientation: 'rl-tb'
            OrangeButton:
                text: "Close"
                width: self.parent.width / 2.5
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.on_close()
            Widget: # Horizontal Spacer
            GreenButton:
                text: "Top-up now"
                width: self.parent.width / 2.5
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.on_top_up()
            
