#:kivy 2.1.0


<LinkCardScreen>:
    rows: 1
    size_hint: (1, 1)
    padding: '20dp'
    canvas:
        Color:
            rgba: app.colors["background"]
        Rectangle:
            pos: self.pos
            size: self.size

    GridLayout:
        rows: 1
        AnchorLayout:
            size_hint: 0.9, 0.9
            anchor_x: 'center'
            anchor_y: 'center'
            GridLayout:
                cols: 1
                padding: '20dp'
                size_hint: 0.95, 0.95
                canvas:
                    Color:
                        rgba: app.colors["secondary_background"]
                    SmoothRoundedRectangle:
                        pos: self.pos
                        size: self.size
                Label:
                    size_hint_y: None
                    height: self.width / 18
                    font_size: self.width / 20
                    text_size: self.size
                    halign: 'center'
                    valign: 'middle'
                    bold: True            
                    text: 'What user do you want to link this card to?'
                Widget: # Vertical Spacer
                    size_hint_y: 0.1
                ClickableTable:
                    id: usersTable
                    headerHeight: self.width / 15
                    entryHeight: self.width / 15
                    columns: ["First name", "Last name", "Card"]
                    columnExamples: ["LongName", "LongLastName", "23234234"]
                    onEntryPressed: root.onUserEntryPressed
                Widget: # Vertical Spacer
                    size_hint_y: 0.1
                GridLayout:
                    rows: 1
                    size_hint: (1, None)
                    height: self.minimum_height
                    orientation: 'rl-tb'
                    OrangeButton:
                        text: "Cancel"
                        width: self.parent.width / 4
                        height: self.width / 3
                        text_size: self.height / 2
                        on_press: root.cancel()

                    
                    


