#:kivy 2.1.0


<LinkCardScreen>:
    rows: 1
    size_hint: (1, 1)
    padding: '20dp'
    canvas:
        Color:
            rgba: app.colors["background"]
        Rectangle:
            pos: self.pos
            size: self.size

    GridLayout:
        rows: 1
        AnchorLayout:
            size_hint: 0.9, 0.9
            anchor_x: 'center'
            anchor_y: 'center'
            GridLayout:
                cols: 1
                padding: '10dp'
                spacing: '10dp'
                size_hint: 0.95, 0.95
                canvas:
                    Color:
                        rgba: app.colors["secondary_background"]
                    SmoothRoundedRectangle:
                        pos: self.pos
                        size: self.size
                Label:
                    size_hint_y: None
                    height: 40
                    font_size: 32
                    text_size: self.size
                    halign: 'center'
                    valign: 'middle'
                    bold: True            
                    text: 'What user do you want to link this card to?'
                GridLayout:
                    cols: 1
                    id: selectUserLayout
                    ClickableTable:
                        id: usersTable
                        headerHeight: 50
                        entryHeight: 50
                        columns: ["First name", "Last name", "Card"]
                        columnExamples: ["LongName", "LongLastName", "23234234"]
                        onEntryPressed: root.onUserEntryPressed
                GridLayout:
                    rows: 1
                    size_hint: (1, None)
                    height: self.minimum_height
                    orientation: 'rl-tb'
                    MediumOrangeButton:
                        text: "Cancel"
                        on_press: root.cancel()

                    
                    


