#:kivy 2.1.0     

<LinkCardConfirmationPopup>:
    size_hint: (0.8, 0.6)
    auto_dismiss: True
    RoundedTwoColorGridLayout:
        center_x: True
        cols: 1
        size_hint: (1, 1)
        padding: '25dp'
        Widget: # Vertical Spacer
            size_hint_y: 0.1
        Label:
            id: title
            size_hint_y: None
            height: (self.width / 14) * 2
            font_size: self.width / 16
            text_size: self.size
            halign: 'center'
            valign: 'middle'
            bold: True            
            text: 'Add/Update linked card'
        Widget: # Vertical Spacer
            size_hint_y: 0.2
        Label:
            id: question
            size_hint_y: None
            height: (self.width / 18) * 2
            font_size: self.width / 20
            text_size: self.size
            halign: 'center'
            valign: 'middle'
            bold: True            
            text: 'UNDEFINED'
        Widget: # Vertical Spacer
            size_hint_y: 0.3
        GridLayout:
            rows: 1
            size_hint: (1, None)
            height: self.minimum_height
            OrangeButton:
                text: "Cancel"
                width: self.parent.width / 4
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.onCancel()
            Widget: # Horizontal Spacer
            GreenButton:
                text: "Confirm"
                width: self.parent.width / 4
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.onConfirm()
            
            
            