#:kivy 2.1.0

<LoginScreenUserWidget>:
    size_hint_x: None
    width: self.height
    ClickableRoundedTwoColorGridLayout:
        id: clickableLayout
        rows: 1
        on_press: root.Clicked()
        Label:
            id: userNameLabel
            text: 'User'
            text_size: self.size
            size: self.texture_size
            halign: 'center'
            valign: 'center'
            font_size: self.width/7
            color : [0,0,0,1]
            bold: True

<LoginScreen>:
    GridLayout:
        cols: 1
        canvas:
            Color:
                rgba: app.colors["background"]
            Rectangle:
                pos: self.pos
                size: self.size
        padding: 30
        spacing: 30

        Label:
            halign: 'center'
            size_hint_y: 0.1
            font_size: self.width/20
            color: 'black'
            bold: True
            text: "Select or create user"
        
        Widget: # Vertical Spacer
            size_hint_y: 0.1
        
        ScrollView:
            id: scrollView
            size_hint_y: 0.5
            do_scroll_y: False
            GridLayout:
                id: LoginScreenUserGridLayout
                rows: 1
                spacing: 30
                padding: [30, 10]
                size_hint_x: None
                width: self.minimum_width
        
        Widget: # Vertical Spacer
            size_hint_y: 0.1
        
        GridLayout:
            rows: 1
            cols: 2
            size_hint_y: 0.2
            spacing: 30
            Widget: # Horizontal Spacer
            ClickableRoundedTwoColorGridLayout:
                rows: 1
                on_press: root.createNewUserButtonClicked()
                Label:
                    id: createUserLabel
                    text: 'Create new user'
                    bold: True
                    color: 'black'
                    font_size: self.width/10
            ClickableRoundedTwoColorGridLayout:
                rows: 1
                on_press: root.guestModeButtonClicked()
                Label:
                    id: guestModeLabel
                    text: 'Guest Mode'
                    bold: True
                    color: 'black'
                    font_size: self.width/10
            Widget: # Horizontal Spacer