#:kivy 2.1.0

<LogScreen>:
    rows: 2
    cols: 1
    NavigationHeader:
        id: header
        use_settings_button: False
        page_name: "Application Logs"
    GridLayout:
        cols: 1
        padding: [10, 5]
        spacing: 5
        canvas:
            Color:
                rgba: app.colors["background"]
            Rectangle:
                pos: self.pos
                size: self.size
        RoundedTwoColorGridLayout:
            rows: 1
            padding: 5
            RecycleView:
                id: logRecycleView
                viewclass: 'LogLine'
                scroll_y: 0
                RecycleBoxLayout:
                    default_size: None, 22
                    default_size_hint: 1, None
                    size_hint_y: None
                    height: self.minimum_height
                    orientation: 'vertical'
        GridLayout:
            rows: 1
            cols: 3
            size_hint_y: None
            height: self.minimum_height
            spacing: 5
            padding: [20, 5]
            Widget:
            RedButton:
                id: clearLogsButton
                text: "Clear Logs"
                height: self.parent.width * 0.1
                width: self.height * 3
                text_size: self.height / 2
            Widget:
