#:kivy 2.1.0     

<GambleOption>:
    image_path: 'Images/roulette.png'
    text: 'Gamble'

<BuyOption>:
    image_path: 'Images/cart-shopping-fast.png'
    text: 'Buy'

<TopUpOption>:
    image_path: 'Images/money-income.png'
    text: 'Top-up'

<ProfileOption>:
    image_path: 'Images/user.png'
    text: 'Profile'



<MainUserScreen>:
    rows: 2
    cols: 1
    NavigationHeader:
        id: header
        use_settings_button: True
        page_name: "Main User Screen"
    GridLayout:
        id: optionsGrid
        rows: 1
        canvas:
            Color:
                rgba: app.colors["background"]
            Rectangle:
                pos: self.pos
                size: self.size
        padding: 30
        spacing: 30
        GambleOption:
            id: gambleOption
        BuyOption:
            id: buyOption
        GridLayout:
            cols: 1
            spacing: 30
            TopUpOption:
                id: topUpOption
            ProfileOption:
                id: profileOption
