#:kivy 2.1.0     

<MainUserScreenContent>:
    rows: 1
    padding: 30
    spacing: 30
    ClickableRoundedTwoColorGridLayout:
        on_press: root.onBuyButtonPressed()
        cols: 1
        padding: [0, 90]
        Image:
            color: 'white'
            height: 98
            size_hint: (1, None)
            source: 'Images/cart-shopping-fast.png'
        Widget: # Horizontal Spacer
            size_hint: (1, 1)
        Label:
            text: 'Buy'
            bold: True
            font_size: "30sp"
            size_hint_y: None
            height: 30
    ClickableRoundedTwoColorGridLayout:
        on_press: root.onTopUpButtonPressed()
        cols: 1
        padding: [0, 90]
        Image:
            color: 'white'
            height: 98
            size_hint: (1, None)
            source: 'Images/money-income.png'
        Widget: # Horizontal Spacer
            size_hint: (1, 1)
        Label:
            text: 'Top-up'
            bold: True
            font_size: "30sp"
            size_hint_y: None
            height: 30
    ClickableRoundedTwoColorGridLayout:
        on_press: root.onHistoryButtonPressed()
        cols: 1
        padding: [0, 90]
        Image:
            color: 'white'
            height: 98
            size_hint: (1, None)
            source: 'Images/time-past.png'
        Widget: # Horizontal Spacer
            size_hint: (1, 1)
        Label:
            text: 'History'
            bold: True
            font_size: "30sp"
            size_hint_y: None
            height: 30