#:kivy 2.1.0     

# Main KV file that imports others
#:include kv/splashScreen.kv
#:include kv/loginScreen.kv
#:include kv/mainUserScreen.kv
#:include kv/createUserScreen.kv
#:include kv/aboutPopup.kv
#:include kv/errorMessagePopup.kv
#:include kv/adminScreen.kv
#:include kv/editSnacksScreen.kv
#:include kv/headerBodyLayout.kv
#:include kv/editUsersScreen.kv
#:include kv/addSnackScreen.kv
#:include kv/topUpAmountScreen.kv
#:include kv/topUpPaymentScreen.kv
#:include kv/buyScreen.kv
#:include kv/editUserScreen.kv
#:include kv/historyScreen.kv
#:include kv/editSnackScreen.kv
#:include kv/purchaseCompletedPopup.kv
