#:kivy 2.1.0     

<ManageDevicesPopupDevice>:
    orientation: 'horizontal'
    size_hint: (1, None)
    height: '50dp'
    padding: [10, 0, 10, 0]
    canvas:
        Color:
            rgba: 0.2, 0.2, 0.2, 0.5
        Rectangle:
            pos: self.pos
            size: self.size
    
    Label:
        id: manageDeviceAddedDeviceName
        text: 'deviceName'
        halign: 'left'
        valign: 'middle'
        size_hint: None, None
        text_size: self.size
        width: '130dp'
        height: '50dp'
    
    Label:
        id: manageDeviceAddedDeviceType
        text: 'deviceType'
        halign: 'left'
        valign: 'middle'
        size_hint: None, None
        text_size: self.size
        width: '130dp'
        height: '50dp'
    
    Button:
        id: manageDeviceAddedDeviceRemoveButton
        text: 'Manage'
        halign: 'center'
        valign: 'middle'
        size_hint: None, None
        text_size: self.size
        width: '100dp'
        height: '50dp'
        on_press: root.OnManageDeviceButtonPressed(root.ids.manageDeviceAddedDeviceName.text)

<ManageDevicePopup>:
    id: manageDevicePopup
    title: 'Manage device'
    height: '320dp'
    width: '300dp'
    size_hint: None, None
    GridLayout:
        cols: 1
        padding: [10, 10, 10, 10]
        spacing: [5, 5]

        BoxLayout:
            id: manageDeviceNameLabel
            size_hint: 1, None
            height: '20dp'
            Label:
                id: addDeviceNameLabel
                halign: 'left'
                text_size: self.size
                text: 'Device Name:'
                
        TextInput:
            id: manageDeviceNameInput
            size_hint: 1, None
            height: '40dp'
            font_size: '20dp'
            multiline: False
            focus: True
            on_text_validate: root.OnConfirmButtonPressed()
        
        BoxLayout:
            id: manageDeviceTypeLabel
            size_hint: 1, None
            height: '20dp'
            Label:
                halign: 'left'
                text_size: self.size
                id: manageDeviceTypeLabel
                text: 'Device Type:'
                size_hint: (1, 1)
        
        Spinner:
            id: manageDeviceTypeSpinner
            size_hint: 1, None
            height: '40dp'
            text: 'UNDEFINED'
            values: ['UNDEFINED']
        
        BoxLayout:
            id: manageDeviceButtonsSpacer
            size_hint: 1, None
            height: '40dp'
        
        GridLayout:
            id: manageDeviceButtonsGrid
            cols: 4
            size_hint: 1, None
            height: '50dp'
            spacing: [10, 10]

            BoxLayoutButton:
                id: manageDeviceRemoveButton
                size_hint: 1, None
                height: '50dp'
                width: '70dp'
                on_press: root.OnRemoveButtonPressed()
                canvas:
                    Color:
                        rgba: 1.0, 0.0, 0.0, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                
                Label:
                    id: manageDeviceRemoveLabel
                    text: 'Remove'
                    size_hint: (1, 1)
            
            BoxLayout:
                id: manageDeviceRemoveButtonSpacer
                size_hint: None, None
                height: '50dp'
                width: '30dp'

            BoxLayoutButton:
                id: manageDeviceCancelButton
                size_hint: 1, None
                height: '50dp'
                width: '70dp'
                on_press: root.dismiss()
                canvas:
                    Color:
                        rgba: 0.7, 0.7, 0.7, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                
                Label:
                    id: manageDeviceCancelLabel
                    text: 'Cancel'
                    size_hint: (1, 1)

            BoxLayoutButton:
                id: manageDeviceConfirmButton
                size_hint: 1, None
                height: '50dp'
                width: '70dp'
                on_press: root.OnConfirmButtonPressed()
                canvas:
                    Color:
                        rgba: 0.7, 0.7, 0.7, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                
                Label:
                    id: manageDeviceRemoveLabel
                    text: 'Confirm'
                    size_hint: (1, 1)
