<PatronRowWidget>:
    orientation: 'horizontal'
    size_hint_min: (1, 0.7)
    size_hint: (1, None)
    height: '96dp'
    canvas:
        Color:
            rgba: 0.2, 0.2, 0.2, 1
        Rectangle:
            pos: self.pos
            size: self.size

<ManagePatronsPopup>:
    id: managePatronsPopup
    title: 'Manage patrons'
    size_hint: (0.8, 0.77)
    
    GridLayout:
        id: verticalLayoutGrid
        cols: 1
        size_hint: (1, 1)
        spacing: [10, 10]
        
        GridLayout:
            id: header
            cols: 3
            size_hint: (1, None)
            padding: [10, 0, 10, 0]
            height: '50dp'
            canvas:
                Color:
                    rgba: 0.4, 0.4, 0.4, 1.0
                Rectangle:
                    pos: self.pos
                    size: self.size
            
            Label:
                id: manageDevicesAddedDevicesGridHeaderDeviceName
                text: 'Name'
                halign: 'left'
                valign: 'middle'
                size_hint: None, None
                text_size: self.size
                width: '130dp'
                height: '50dp'

            Label:
                id: manageDevicesAddedDevicesGridHeaderDeviceType
                text: 'Subscription end date'
                halign: 'left'
                valign: 'middle'
                size_hint: None, None
                text_size: self.size
                width: '100dp'
                height: '50dp'
                canvas:

            Label:
                id: manageDevicesAddedDevicesGridHeaderDeviceType
                text: 'Current subscriber'
                halign: 'left'
                valign: 'middle'
                size_hint: None, None
                text_size: self.size
                width: '90dp'
                height: '50dp'

        ScrollView:
            id: manageDevicesAddedDevicesGridList
            size_hint: (1, None)
            height: '200dp'
            do_scroll_x: False
            do_scroll_y: True

            GridLayout:
                id: manageDevicesAddedDevicesGridListContent
                cols: 3
                size_hint_y: None
                size_hint_x: 1
                height: self.minimum_height
                row_default_height: '50dp'
                
        BoxLayoutButton:
            id: manageDevicesAddDeviceBox
            size_hint: (None, None)
            height: '30dp'
            width: '130dp'
            on_press: root.OnAddDeviceButtonPressed()
            canvas:
                Color:
                    rgba: 0.4, 0.4, 0.4, 1.0
                Rectangle:
                    pos: self.pos
                    size: self.size
            
            Label:
                id: manageDevicesAddDeviceLabel
                text: 'Add new patron'
                size_hint: (1, 1)

<AddPatronPopup>:
    id: AddPatronPopup
    title: 'Add a Patron'
    height: '320dp'
    width: '400dp'
    size_hint: None, None
    GridLayout:
        cols: 1
        padding: [10, 10, 10, 10]
        spacing: [10, 10]

        BoxLayout:
            id: addPatronInputLabel
            size_hint: 1, None
            height: '20dp'
            Label:
                halign: 'left'
                text_size: self.size
                text: 'Enter Patron Details:'
        
        BoxLayout:
            id: addPatronInputs
            size_hint: 1, None
            height: '40dp'
            spacing: '10dp'  # Space between input fields
            
            TextInput:
                id: addPatronFirstNameInput
                size_hint: 1, 1
                font_size: '16dp'
                multiline: False
                hint_text: 'First Name'
            
            TextInput:
                id: addPatronLastNameInput
                size_hint: 1, 1
                font_size: '16dp'
                multiline: False
                hint_text: 'Last Name'
            
            TextInput:
                id: addPatronEmployeeIDInput
                size_hint: 1, 1
                font_size: '16dp'
                multiline: False
                hint_text: 'Employee ID'

        BoxLayout:
            id: addDeviceAddButtonSpacer
            size_hint: 1, None
            height: '20dp'
        
        BoxLayoutButton:
            id: addDeviceAddButton
            size_hint: 1, None
            height: '50dp'
            on_press: root.AddPatron()
            canvas:
                Color:
                    rgba: 0.7, 0.7, 0.7, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                id: addDeviceAddLabel
                text: 'Add Patron'
                size_hint: (1, 1)
