#:kivy 2.1.0     

<PurchaseCompletedPopup>:
    size_hint: (0.8, 0.5)
    auto_dismiss: True
    GridLayout:
        canvas:
            Color:
                rgba: (1, 1, 1, 1)
            SmoothRoundedRectangle:
                pos: self.pos
                size: self.size
            Color:
                rgba: app.colors["button"]
            SmoothRoundedRectangle:
                pos: (self.pos[0] + 5, self.pos[1] + 5)
                size: (self.width - 10, self.height - 10)
        center_x: True
        cols: 1
        size_hint: (1, 1)
        BoxLayout:
            orientation: "vertical"
            size_hint: (1, .9)
            Label:
                text_size: self.size
                padding: 10
                halign: 'center'
                valign: 'middle'
                font_size: 42
                bold: True
                text: 'Thank you for your purchase!'
                
            Label:
                id: creditsLabel
                text_size: self.size
                padding: 10
                halign: 'center'
                valign: 'middle'
                font_size: 32
                bold: True
                text: 'Your credits: ??'