#:kivy 2.1.0     

<PurchaseSummaryHeading@Label>:
    font_size: self.width / 18
    text_size: self.size
    size_hint_y: None
    height: self.width / 16
    halign: 'left'
    valign: 'middle'
    bold: True

<PurchaseSummaryData@Label>:
    font_size: self.width / 20
    text_size: self.size
    size_hint_y: None
    height: self.width / 18
    halign: 'left'
    valign: 'middle'

<PurchaseSummaryPopup>:
    size_hint: (0.9, None)
    auto_dismiss: True
    GridLayout:
        cols: 1
        id: purchaseSummaryPopupContent
        size_hint_y: None
        height: self.minimum_height
        padding: 10
        spacing: 10
        canvas:
            Color:
                rgba: app.colors["secondary_background"]
            SmoothRoundedRectangle:
                pos: self.pos
                size: self.size
        GridLayout:
            rows: 1
            size_hint_y: None
            height: self.minimum_height
            GridLayout:
                cols: 1
                size_hint_y: None
                size_hint_x: 0.5
                height: self.minimum_height
                spacing: 10
                GridLayout:
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 5
                    PurchaseSummaryHeading:
                        text: 'Purchase date:'
                    PurchaseSummaryData:
                        text: 'DATA NOT SET'
                        id: purchaseDateLabel
                GridLayout:
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 5
                    PurchaseSummaryHeading:
                        text: 'Credits before purchase:'
                    PurchaseSummaryData:
                        text: 'DATA NOT SET'
                        id: creditsBeforeLabel
                GridLayout:
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 5
                    PurchaseSummaryHeading:
                        text: 'Credits after purchase:'
                    PurchaseSummaryData:
                        text: 'DATA NOT SET'
                        id: creditsAfterLabel
                GridLayout:
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 5
                    PurchaseSummaryHeading:
                        text: 'Total number of items bought:'
                    PurchaseSummaryData:
                        text: 'DATA NOT SET'
                        id: numberOfItemsBoughtLabel
                GridLayout:
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 5
                    PurchaseSummaryHeading:
                        text: 'Total price of items bought:'
                    PurchaseSummaryData:
                        text: 'DATA NOT SET'
                        id: totalPriceLabel
            GridLayout:
                id: purchaseSummaryContent
                cols: 1
                size_hint_x: 0.5
                spacing: 5
                Label:
                    size_hint_y: None
                    font_size: self.width / 22
                    text_size: self.size
                    size_hint_y: None
                    height: self.width / 20
                    text: "Items bought:"
                    bold: True
                ClickableTable:
                    id: itemsBoughtTable
                    headerHeight: self.width / (15 / 2)
                    entryHeight: self.width / (15 / 2)
                    columns: ["Snack name", "Quantity", "Price"]
                    columnExamples: ["Long name", "100", "43.43"]
        GridLayout:
            rows: 1
            size_hint: (1, None)
            height: self.minimum_height
            orientation: 'rl-tb'
            OrangeButton:
                text: "Close"
                width: self.parent.width / 4
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.dismiss()