#:kivy 2.1.0

<RemoveConfirmationPopup>:
    size_hint: (0.8,0.6)
    canvas:
        Color:
            rgba: app.colors["secondary_background"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        cols: 1
        padding: 30
        spacing: 30
        Label:
            id: question_label
            text_size: self.size
            font_size: self.width / 16
            halign: 'center'
            valign: 'middle'
            text: "Are you sure you?"
            bold: True
        GridLayout:
            rows: 1
            size_hint: (1, None)
            height: self.minimum_height
            Widget: # Horizontal Spacer
            RedButton:
                id: remove_button
                text: "Remove"
                width: self.parent.width / 3
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.remove_button_pressed()
            Widget: # Horizontal Spacer
            OrangeButton:
                text: "Cancel"
                width: self.parent.width / 3
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.cancel_button_pressed()
            Widget: # Horizontal Spacer
            
            
