<SnackAttackTrackWidget>:
    orientation: "vertical"
    BoxLayout:
        canvas:
            Color:
                rgba: .8, .8, .8, 1
            Rectangle:
                pos: self.pos
                size: self.size
        orientation: "horizontal"
        size_hint: 1, None
        height: '48dp'
        GridLayout:
            id: leftIconGrid
            orientation: "lr-tb"
            rows: 1
            size_hint: 1, 1
            ImageButton:
                source: 'Images/ghost_happy.png'
                color: 'white'
                width: '48dp'
                size_hint_x: None
                on_press: root.displayAboutPopup()
            Label:
                id: heading
                text: 'Snack Attack Track'
                size_hint: (1, 1)
                color: 'black'
                bold: True
        GridLayout:
            id: rightIconGrid
            orientation: "rl-tb"
            rows: 1
            size_hint: 1, 1

            ImageButton:
                id: manageDevicesButton
                width: '48dp'
                size_hint_x: None
                source: 'Images/manage_devices.png'
                color: 'white'
                on_press: root.OnManagePatronsButtonPressed()
    
    GridLayout:
        id: patronList
        cols: 1
        spacing: 10
        size_hint:(1,1)
        canvas:
            Color:
                rgba: 0, 0.3, 0, 1
            Rectangle:
                pos: self.pos
                size: self.size
