#:kivy 2.1.0     

<SplashScreenWidget>:
    ImageButton:
        source: 'Images/background.gif'
        fit_mode: 'fill'
        color: 'white'
        on_press: root.onPressed()
        Label:
            text: 'Tap to login or create user...'
            text_size: self.size
            size: self.texture_size
            halign: 'center'
            valign: 'middle'
            font_size: 40
            color : [0,0,0,1]
            bold: True