#:kivy 2.1.0     

<SplashScreenWidget>:
    Button:
        id: splashButton
        on_press: root.onPressed()
        StackLayout:
            pos: self.parent.pos
            size: self.parent.size
            orientation: 'lr-tb'
            Image:
                source: 'Images/background.gif'
                fit_mode: 'fill'
                color: 'white'
    GridLayout:
        cols: 1
        padding: [0, 150]
        Image:
            source: 'Images/logo_type.png'
            size: self.texture_size
        Label:
            halign: 'center'
            size_hint: (1, None)
            height: 28
            font_size: 27
            color: 'black'
            bold: True
            text: "Tap to login or create user..."