#:kivy 2.1.0     

<StoreStatisticsScreen>:
    rows: 2
    cols: 1
    NavigationHeader:
        id: header
        use_settings_button: False
        page_name: "Store Statistics"
    GridLayout:
        rows: 1
        padding: (self.width / 28, self.height / 8)
        spacing: 30
        canvas:
            Color:
                rgba: app.colors["background"]
            Rectangle:
                pos: self.pos
                size: self.size
        GridLayout:
            rows: 2
            cols: 3
            spacing: 30
            DoubleStatWidget:
                id: added_stats
                stat_name: "Added"
                stat_value_1: "-1 Snacks"
                stat_value_2: "-1 Credits"
            DoubleStatWidget:
                id: inventory_stats
                stat_name: "Inventory"
                stat_value_1: "-1 Snacks"
                stat_value_2: "-1 Credits"
            DoubleHeaderValueStatWidget:
                id: gambling_stats
                stat_name_1: "Gambling wagers"
                stat_value_1: "-1 Credits"
                stat_name_2: "Gambling returns"
                stat_value_2: "-1 Credits"
            DoubleStatWidget:
                id: lost_stats
                stat_name: "Lost/Stolen"
                stat_value_1: "-1 Snacks"
                stat_value_2: "-1 Credits"
            DoubleStatWidget:
                id: sold_stats
                stat_name: "Sold"
                stat_value_1: "-1 Snacks"
                stat_value_2: "-1 Credits"
            SingleStatWidget:
                id: profit_stat
                stat_name: "Total profit"
                stat_value: "-1 Credits"
