#:kivy 2.1.0     

<TopUpSwishCommerceScreen>:
    rows: 2
    cols: 1
    NavigationHeader:
        id: header
        use_settings_button: False
        page_name: "Top-up (Swish Commerce)"
    GridLayout:
        rows: 1
        padding: 30
        spacing: 30
        canvas:
            Color:
                rgba: app.colors["background"]
            Rectangle:
                pos: self.pos
                size: self.size
        GridLayout:
            cols: 1
            Image:
                id: qrCodeImage
                source: ""
                allow_stretch: True
                keep_ratio: True
        GridLayout:
            cols: 1
            spacing: 10
            RoundedTwoColorGridLayout:
                cols: 1
                #spacing: 10
                padding: [0, 20]
                GridLayout:
                    cols: 1
                    size_hint_y: 0.35
                    Label:
                        bold: True
                        text: "Step 1:"
                        font_size: self.width/12
                    Label:
                        text: "Scan QR code with swish"
                        font_size: self.width/12
                GridLayout:
                    cols: 1
                    size_hint_y: 0.35
                    Label:
                        bold: True
                        text: "Step 2:"
                        font_size: self.width/12
                    Label:
                        text: "Send payment"
                        font_size: self.width/12
                Widget:
                    size_hint_y: 0.05
                GridLayout:
                    rows: 1
                    size_hint_y: 0.2
                    Widget:
                        size_hint_x: 0.1
                    Label:
                        canvas.before:
                            Color:
                                rgba: app.colors["secondary_background"]
                            Rectangle:
                                pos: self.pos
                                size: self.size
                        id: statusLabel
                        text: "Creating payment request..."
                        font_size: self.height / 2
                        halign: 'center'
                        valign: 'middle'
                        size_hint_x: 0.8
                        size_hint_y: None
                        height: self.width / 8
                    Widget:
                        size_hint_x: 0.1
                Widget:
                    size_hint_y: 0.05
            GridLayout:
                rows: 1
                size_hint: (1, None)
                height: self.minimum_height
                Widget:
                OrangeButton:
                    id: cancelButton
                    width: self.parent.width / 2.5
                    height: self.width / 3
                    text_size: self.height / 2
                    text: "Cancel"
                    on_release: root.onCancel()
                Widget:
