#:kivy 2.1.0     

<TopUpSummaryHeading@Label>:
    font_size: self.width / 20
    text_size: self.size
    size_hint_y: None
    height: self.width / 18
    halign: 'left'
    valign: 'middle'
    bold: True

<TopUpSummaryData@Label>:
    font_size: self.width / 22
    text_size: self.size
    size_hint_y: None
    height: self.width / 20
    halign: 'left'
    valign: 'middle'

<TopUpSummaryPopup>:
    size_hint: (0.5, None)
    auto_dismiss: True
    GridLayout:
        cols: 1
        id: topUpSummaryPopupContent
        size_hint_y: None
        height: self.minimum_height
        padding: 10
        spacing: 10
        canvas:
            Color:
                rgba: app.colors["secondary_background"]
            SmoothRoundedRectangle:
                pos: self.pos
                size: self.size
        GridLayout:
            cols: 1
            size_hint_y: None
            height: self.minimum_height
            spacing: 10
            GridLayout:
                cols: 1
                size_hint_y: None
                spacing: 5
                height: self.minimum_height
                TopUpSummaryHeading:
                    text: 'Top-up date:'
                TopUpSummaryData:
                    text: 'DATA NOT SET'
                    id: topUpDateLabel
            GridLayout:
                cols: 1
                size_hint_y: None
                spacing: 5
                height: self.minimum_height
                TopUpSummaryHeading:
                    text: 'Credits before Top-up:'
                TopUpSummaryData:
                    text: 'DATA NOT SET'
                    id: creditsBeforeTopUpLabel
            GridLayout:
                cols: 1
                size_hint_y: None
                spacing: 5
                height: self.minimum_height
                TopUpSummaryHeading:
                    text: 'Credits after Top-up:'
                TopUpSummaryData:
                    text: 'DATA NOT SET'
                    id: creditsAfterTopUpLabel
        GridLayout:
            rows: 1
            size_hint: (1, None)
            height: self.minimum_height
            orientation: 'rl-tb'
            SmallOrangeButton:
                text: "Close"
                width: self.parent.width / 2.5
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.dismiss()