#:kivy 2.1.0     

<TopUpPaymentScreenContent>:
    rows: 1
    padding: 30
    spacing: 30
    GridLayout:
        cols: 1
        id: qrCodeLayout
    GridLayout:
        cols: 1
        spacing: 10
        RoundedTwoColorGridLayout:
            cols: 1
            spacing: 10
            padding: [0, 20]
            GridLayout:
                cols: 1
                Label:
                    bold: True
                    text: "Step 1:"
                    font_size: 28
                Label:
                    text: "Scan QR code with swish"
                    font_size: 28
            GridLayout:
                cols: 1
                Label:
                    bold: True
                    text: "Step 2:"
                    font_size: 28
                Label:
                    text: "Send payment"
                    font_size: 28
            GridLayout:
                cols: 1
                Label:
                    bold: True
                    text: "Step 3:"
                    font_size: 28
                Label:
                    text: "Click confirm below"
                    font_size: 28
        GridLayout:
            rows: 1
            size_hint: (1, None)
            height: self.minimum_height
            SmallGreenButton:
                text: "Confirm"
                on_press: root.onConfirm()
            Widget: # Horizontal Spacer
                size_hint: (1, None)
                height: 50
            SmallOrangeButton:
                text: "Cancel"
                on_press: root.onCancel()
                