#:kivy 2.1.0     

<TopUpAmountScreenContent>:
    cols: 1
    padding: 30
    spacing: 30
    GridLayout:
        rows: 1
        size_hint: (1, 0.5)
        padding: [40, 0, 40, 60]
        GridLayout:
            cols: 1
            Label:
                size_hint: (1, 0.3)
                font_size: 32
                bold: True
                halign: 'center'
                text: "Current \ncredits:"
            TextInput:
                id: creditsCurrent
                disabled: True
                write_tab: False
                hint_text: "??"
                size_hint_y: None
                height: 40
                padding: [10, 10]
        GridLayout:
            cols: 1
            Label:
                font_size: 32
                bold: True
                text: "+"
        GridLayout:
            cols: 1
            Label:
                font_size: 32
                bold: True
                halign: 'center'
                text: "Add \ncredits:"
            TextInput:
                id: creditsToAdd
                write_tab: False
                hint_text: "Enter amount"
                size_hint_y: None
                height: 40
                padding: [10, 10]
        GridLayout:
            cols: 1
            Label:
                font_size: 32
                bold: True
                text: "="
        GridLayout:
            cols: 1
            Label:
                font_size: 32
                bold: True
                halign: 'center'
                text: "Credits \nafterwards:"
            TextInput:
                id: creditsAfterwards
                disabled: True
                write_tab: False
                hint_text: "??"
                size_hint_y: None
                height: 40
                padding: [10, 10]
    
    GridLayout:
        size_hint: (1, None)
        height: self.minimum_height
        rows: 1
        padding: [30, 0]
        LargeConfirmButton:
            anchor_x: "left"
            on_press: root.onConfirm()
        Widget: # Horizontal Spacer
            size_hint: (1, None)
            height: 100
        LargeCancelButton:
            anchor_x: "right"
            on_press: root.onCancel()