#:kivy 2.1.0     

<TopUpAmountScreenContent>:
    cols: 1
    padding: 30
    spacing: 30
    GridLayout:
        canvas.before:
            Color:
                rgba: 0, 0, 0, 0.10
            BoxShadow:
                pos: self.pos
                size: self.size
                offset: 10, -10
                blur_radius: 15
                spread_radius: -5, -5
                border_radius: 10, 10, 10, 10
        canvas:
            Color:
                rgba: (1, 1, 1, 1)
            SmoothRoundedRectangle:
                pos: self.pos
                size: self.size
            Color:
                rgba: app.colors["button"]
            SmoothRoundedRectangle:
                pos: (self.pos[0] + 5, self.pos[1] + 5)
                size: (self.width - 10, self.height - 10)
        rows: 1
        size_hint: (1, 0.5)
        padding: [40, 30, 40, 40]
        GridLayout:
            cols: 1
            Label:
                size_hint: (1, 0.3)
                font_size: 32
                bold: True
                halign: 'center'
                text: "Current \ncredits:"
            TextInput:
                id: creditsCurrent
                disabled: True
                write_tab: False
                hint_text: "??"
                size_hint_y: None
                height: 40
                padding: [10, 10]
        GridLayout:
            cols: 1
            Label:
                font_size: 32
                bold: True
                text: "+"
        GridLayout:
            cols: 1
            Label:
                font_size: 32
                bold: True
                halign: 'center'
                text: "Add \ncredits:"
            TextInput:
                id: creditsToAdd
                write_tab: False
                multiline: False
                hint_text: "Enter amount"
                input_filter: "float"
                size_hint_y: None
                height: 40
                padding: [10, 10]
        GridLayout:
            cols: 1
            Label:
                font_size: 32
                bold: True
                text: "="
        GridLayout:
            cols: 1
            Label:
                font_size: 32
                bold: True
                halign: 'center'
                text: "Credits \nafterwards:"
            TextInput:
                id: creditsAfterwards
                disabled: True
                write_tab: False
                hint_text: "??"
                size_hint_y: None
                height: 40
                padding: [10, 10]
    
    GridLayout:
        size_hint: (1, None)
        height: self.minimum_height
        rows: 1
        padding: [30, 0]
        LargeConfirmButton:
            anchor_x: "left"
            on_press: root.onConfirm()
        Widget: # Horizontal Spacer
            size_hint: (1, None)
            height: 100
        LargeCancelButton:
            anchor_x: "right"
            on_press: root.onCancel()