#:kivy 2.1.0     

<SingleStatWidget>:
    rows: 2
    cols: 1
    padding: self.height / 20
    canvas:
        Color:
            rgba: app.colors["secondary_background"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [(20, 20),(20, 20),(20, 20),(20, 20)]
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.10
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: 10, -10
            blur_radius: 15
            spread_radius: -5, -5
            border_radius: 20, 20, 20, 20
    Label:
        text: root.stat_name
        font_size: self.height / 3
        align: "left"
        valign: "middle"
        bold: True
    Label:
        text: root.stat_value
        font_size: self.height / 3
        align: "left"
        valign: "middle"

<UserStatisticsScreen>:
    rows: 2
    cols: 1
    NavigationHeader:
        id: header
        use_settings_button: False
        page_name: "User Statistics"
    GridLayout:
        cols: 2
        rows: 2
        padding: (self.width / 8, self.height / 8)
        spacing: 30
        canvas:
            Color:
                rgba: app.colors["background"]
            Rectangle:
                pos: self.pos
                size: self.size
        SingleStatWidget:
            id: total_credits_spent
            stat_name: "Total credits spent"
            stat_value: "$123.45"
        SingleStatWidget:
            id: favorite_snack
            stat_name: "Favorite snack"
            stat_value: "Chips"
        SingleStatWidget:
            id: total_snacks_purchased
            stat_name: "Total snacks purchased"
            stat_value: "67"
        SingleStatWidget:
            id: total_snacks_won
            stat_name: "Total snacks won"
            stat_value: "12"
