#:kivy 2.1.0     

<WheelPointer>:
    angle: root.angle if hasattr(root, 'angle') else 0
    canvas.before:
        PushMatrix
        Rotate:
            angle: root.angle % 360
            axis: 0, 0, 1
            origin: root.center
        Color:
            rgba: (0, 0, 0, 1)
        SmoothTriangle:
            points: (root.x, root.top, root.x, root.y, root.right, root.center_y)
    canvas.after:
        PopMatrix

<WheelWidget>:
    angle: root.angle if hasattr(root, 'angle') else 0
    canvas.before:
        PushMatrix
        Rotate:
            angle: root.angle % 360
            axis: 0, 0, 1
            origin: root.center
    canvas.after:
        PopMatrix
        
<WheelOfSnacksWidget>:
    anchor_x: 'center'
    anchor_y: 'center'
    RelativeLayout:
        id: wheel_layout
        size_hint: (1, None)
        height: min(self.parent.size)*0.90
        WheelWidget:
            id: wheel
            size_hint: (None, None)
            size: (min(self.parent.size), min(self.parent.size))
            pos_hint: {'center_y': 0.5}
            x: (self.parent.width-self.width)/2 + min(self.parent.height, self.parent.width)/24
        WheelPointer:
            id: pointer
            size_hint: (None, None)
            width: min(self.parent.height, self.parent.width)/12
            height: self.width
            pos_hint: {'center_y': 0.5}
            x: (self.parent.width/2) - (min(self.parent.size)/2) - self.width/2

<WheelOfSnacksContent>:
    rows: 1
    padding: 30
    spacing: 20
    GridLayout:
        cols: 1
        Label:
            size_hint_y: None
            height: self.parent.width / 10
            font_size: self.parent.width / 12
            text_size: self.size
            text: "Spin to win!"
            halign: 'center'
            bold: True
            color: "black"
        GridLayout:
            canvas:
                Color:
                    rgba: app.colors["secondary_background"]
                SmoothRoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [(2, 2),(2, 2),(2, 2),(2, 2)]
        Label:
            id: cost_label
            size_hint_y: None
            height: self.parent.width / 14
            font_size: self.parent.width / 16
            text: "One spin costs: ??.?? Credits"
            color: "black"
        
        Widget:
            size_hint_y: 0.2
        GridLayout:
            rows: 1
            size_hint_y: None
            height: self.minimum_height
            Widget:
            SmallGreenButton:
                text: "Spin!"
                width: self.parent.width / 2
                height: self.width / 3
                text_size: self.height / 2
                on_press: root.onSpinButtonPressed()
            Widget:
    WheelOfSnacksWidget:
        id: wheel_widget
        
        