#:kivy 2.1.0     

<ConfirmButton>
    canvas:
        Color:
            rgba: app.colors["green_button"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
    text_size: 16
    Label:
        bold: True
        text: 'Confirm'
        font_size: root.text_size
        size_hint: (1, 1)

<SmallConfirmButton@ConfirmButton>:
    size_hint: (None, None)
    width: 150
    height: 50
    text_size: 22

<MediumConfirmButton@ConfirmButton>:
    size_hint: (None, None)
    width: 200
    height: 75
    text_size: 28

<LargeConfirmButton@ConfirmButton>:
    size_hint: (None, None)
    width: 300
    height: 100
    text_size: 42


<BuyButton>
    canvas:
        Color:
            rgba: app.colors["green_button"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
    text_size: 16
    Label:
        bold: True
        text: 'Buy'
        font_size: root.text_size
        size_hint: (1, 1)

<SmallBuyButton@BuyButton>:
    size_hint: (None, None)
    width: 150
    height: 50
    text_size: 22


<CancelButton>
    canvas:
        Color:
            rgba: app.colors["orange_button"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
    text_size: 16
    Label:
        bold: True
        text: 'Cancel'
        font_size: root.text_size
        size_hint: (1, 1)

<SmallCancelButton@CancelButton>:
    size_hint: (None, None)
    width: 150
    height: 50
    text_size: 22

<MediumCancelButton@CancelButton>:
    size_hint: (None, None)
    width: 200
    height: 75
    text_size: 28

<LargeCancelButton@CancelButton>:
    size_hint: (None, None)
    width: 300
    height: 100
    text_size: 42


<CloseButton>:
    canvas:
        Color:
            rgba: app.colors["orange_button"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
    text_size: 16
    Label:
        bold: True
        text: 'Close'
        font_size: root.text_size
        size_hint: (1, 1)

<SmallCloseButton@CloseButton>:
    size_hint: (None, None)
    width: 150
    height: 50
    text_size: 22


<RemoveButton>:
    canvas:
        Color:
            rgba: app.colors["red_button"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
    text_size: 16
    Label:
        bold: True
        text: 'Remove'
        font_size: root.text_size
        size_hint: (1, 1)

<MediumRemoveButton@RemoveButton>:
    size_hint: (None, None)
    width: 200
    height: 75
    text_size: 28


<RegisterButton>:
    canvas:
        Color:
            rgba: app.colors["green_button"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
    text_size: 16        
    Label:
        bold: True
        text: 'Register'
        font_size: root.text_size
        size_hint: (1, 1)

<LargeRegisterButton@RegisterButton>:
    size_hint: (None, None)
    width: 300
    height: 100
    text_size: 42