#:kivy 2.1.0     

<GreenButton>:
    text: "UNDEFINED"
    text_size: 16
    size_hint: (None, None)
    canvas:
        Color:
            rgba: app.colors["green_button"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
    Label:
        bold: True
        text: root.text
        font_size: root.text_size
        size_hint: (1, 1)

<SmallGreenButton@GreenButton>:
    width: 150
    height: 50
    text_size: 22
    text: "UNDEFINED"

<MediumGreenButton@GreenButton>:
    width: 200
    height: 75
    text_size: 28
    text: "UNDEFINED"

<LargeGreenButton@GreenButton>:
    width: 300
    height: 100
    text_size: 42
    text: "UNDEFINED"


<OrangeButton>:
    text: "UNDEFINED"
    text_size: 16
    size_hint: (None, None)
    canvas:
        Color:
            rgba: app.colors["orange_button"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
    Label:
        bold: True
        text: root.text
        font_size: root.text_size
        size_hint: (1, 1)

<SmallOrangeButton@OrangeButton>:
    width: 150
    height: 50
    text_size: 22
    text: "UNDEFINED"

<MediumOrangeButton@OrangeButton>:
    width: 200
    height: 75
    text_size: 28
    text: "UNDEFINED"

<LargeOrangeButton@OrangeButton>:
    width: 300
    height: 100
    text_size: 42
    text: "UNDEFINED"


<RedButton>:
    text: "UNDEFINED"
    text_size: 16
    size_hint: (None, None)
    canvas:
        Color:
            rgba: app.colors["red_button"]
        SmoothRoundedRectangle:
            pos: self.pos
            size: self.size
    Label:
        bold: True
        text: root.text
        font_size: root.text_size
        size_hint: (1, 1)

<SmallRedButton@RedButton>:
    width: 150
    height: 50
    text_size: 22
    text: "UNDEFINED"

<MediumRedButton@RedButton>:
    width: 200
    height: 75
    text_size: 28
    text: "UNDEFINED"

<LargeRedButton@RedButton>:
    width: 300
    height: 100
    text_size: 42
    text: "UNDEFINED"


<ImageAndTextButton>:
    cols: 1
    Widget: # Horizontal Spacer
        size_hint_y: 0.2
    Image:
        id: image
        size_hint_y: 0.3
        fit_mode: 'contain'
        mipmap: True
        source: root.image_path if hasattr(root, 'image_path') else 'Images/user.png'
    Widget: # Horizontal Spacer
        size_hint_y: 0.2
    Label:
        id: text
        text: root.text if hasattr(root, 'text') else 'OPTION'
        bold: True
        font_size: self.width/8
        size_hint_y: 0.2
    Widget: # Horizontal Spacer
        size_hint_y: 0.1