#:kivy 2.1.0     

<NavigationHeader>:
    rows: 1
    size_hint: 1, 0.2
    canvas:
        Color:
            rgba: 0.392, 0.839, 0.859, 1
        Rectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        id: leftContent
        orientation: "lr-tb"
        padding: 10
        spacing: 10
        rows: 1
        NavigationBackButton:
            id: backButton
        GridLayout:
            cols: 1
            Label:
                id: welcomeTextLabel
                text: app.screenManager.getCurrentPatron().firstName if app.screenManager.getCurrentPatron() else "Welcome, Guest"
                halign: 'left'
                valign: 'middle'
                font_size: min(self.height/1.3, self.width/25)
                text_size: self.size
                color: 'black'
                bold: True
            Label:
                id: patronCreditsLabel
                text: 'Your credits: UNKNOWN'
                halign: 'left'
                valign: 'middle'
                font_size: min(self.height/1.3, self.width/25)
                text_size: self.size
                color: 'black'
                bold: True
    GridLayout:
        id: rightContent
        orientation: "rl-tb"
        rows: 1
        size_hint_x: None
        padding: 10
        spacing: 10
        width: self.minimum_width
        GridLayout:
            rows: 1
            size_hint: None, 1
            width: self.height*2
            BoxLayoutButton:
                id: logoutButton
                canvas:
                    Color:
                        rgba: app.colors["red_button"]
                    SmoothRoundedRectangle:
                        pos: self.pos
                        size: self.size
                Label:
                    text: 'Log out'
                    font_size: self.height/2
                    bold: True
                    size_hint: (1, 1)

<NavigationSettingsButton>:
    size_hint_x: None
    width: self.height
    GridLayout:
        cols: 1
        Image: 
            source: 'Images/wrench-alt.png'
            
<NavigationBackButton>:
    size_hint_x: None
    width: self.height
    GridLayout:
        cols: 1
        Image: 
            source: 'Images/leftArrow.png'
