#:kivy 2.1.0     

<TextInputWithHeader>:
    size_factor: 16
    header_text: "UNDEFINED"
    hint_text: "UNDEFINED"
    input_filter: None
    disable_input: False
    cols: 1
    size_hint: (1, None)
    height: self.minimum_height
    Label:
        id: header
        text_size: self.size
        size_hint_y: None
        font_size: root.size_factor
        height: root.size_factor
        text: root.header_text
        bold: True
    TextInput:
        id: input
        write_tab: False
        multiline: False
        hint_text: root.hint_text
        size_hint_y: None
        font_size: root.size_factor
        input_filter: root.input_filter
        disabled: root.disable_input
        height: self.minimum_height

<LargeTextInputWithHeader>:
    size_factor: 24

<TextInputPopup>:
    size_hint: (0.9, 0.9)
    auto_dismiss: True
    GridLayout:
        cols: 1
        canvas:
            Color:
                rgba: app.colors["secondary_background"]
            SmoothRoundedRectangle:
                pos: self.pos
                size: self.size
        GridLayout:
            rows: 1
            Widget: # Horizontal Spacer
                size_hint: (0.2, 1)
            GridLayout:
                cols: 1
                Widget: # Vertical Spacer
                    size_hint: (1, 0.4)
                LargeTextInputWithHeader:
                    size_factor: 48
                    id: textInput
                    enableVirtualKeyboardEntry: False
                Widget: # Vertical Spacer
                    size_hint: (1, 0.4)
            Widget: # Horizontal Spacer
                size_hint: (0.2, 1)
        GridLayout:
            rows: 1
            id: keyboardLayout
            VKeyboard:
                id: virtualKeyboard
                width: self.parent.width
                height: self.parent.height
                layout: "keyboards/swedishKeyboardLayout.json"
                on_key_up: root.virtualKeyboardInputUp
